### ISSUE TITLE
Filling arrays

### ISSUE THREAD

**Issue by GLinnik21** [intargio/python_courses#16]
### Task
Fill in the array with these N integer numbers and print to the screen:

- [x] 1. numbers entered by the user `1 2 3 4 100500`
- [x] 2. ascending numbers `1 2 3 4 5 6 7`
- [x] 3. even numbers `2 4 6 8 10`
- [x] 4. odd numbers `1 3 5 7 9`
- [x] 5. numbers of the power of two `1 2 4 8 16 32`
- [ ] 6. Fibonacci numbers `1 1 2 3 5 8`
- [x] 7. five decreasing numbers starting with N `10 9 8 7 6 5`
- [x] 8. alternation of 0 and 1 `0 1 0 1 0 1 0 1`
- [x] 9. ascending and decreasing numbers `1 2 3 4 5 4 3 2 1`
- [x] 10. random numbers `5 12 426 85 3 1 4`
